taskid: SpeechBrain_04
result: test_results/SpeechBrain_04/results.jsonl
output_dir: output/SpeechBrain_04/
groundtruth: groundtruth/SpeechBrain_04/gt.wav
test_script: test_scripts/SpeechBrain_04/test_script.py
multi_output: false


