taskid: Eparse_02
result: test_results/Eparse_02/results.jsonl
output_dir: output/Eparse_02/
groundtruth: groundtruth/Eparse_02/gt.txt
test_script: test_scripts/Eparse_02/test_script.py
multi_output: false
