taskid: SpeechBrain_01
result: test_results/SpeechBrain_01/results.jsonl
output_dir: output/SpeechBrain_01/
groundtruth: groundtruth/SpeechBrain_01/
test_script: test_scripts/SpeechBrain_01/test_script.py
multi_output: true


