taskid: SpeechBrain_02
result: test_results/SpeechBrain_02/results.jsonl
output_dir: output/SpeechBrain_02/
groundtruth: groundtruth/SpeechBrain_02/
test_script: test_scripts/SpeechBrain_02/test_script.py
multi_output: true


