taskid: Eparse_03
result: test_results/Eparse_03/results.jsonl
output_dir: output/Eparse_03/
groundtruth: groundtruth/Eparse_03/gt.json
test_script: test_scripts/Eparse_03/test_script.py
multi_output: false
