taskid: NeuroKit_01
result: test_results/NeuroKit_01/results.jsonl
output_dir: output/NeuroKit_01/
groundtruth: groundtruth/NeuroKit_01/gt.csv
test_script: test_scripts/NeuroKit_01/test_script.py
multi_output: false
