taskid: SpeechBrain_03
result: test_results/SpeechBrain_03/results.jsonl
output_dir: output/SpeechBrain_03/
groundtruth: groundtruth/SpeechBrain_03/gt.txt
test_script: test_scripts/SpeechBrain_03/test_script.py
multi_output: false


