taskid: AnimeGANv3_02
result: test_results/AnimeGANv3_02/results.jsonl
output_dir: output/AnimeGANv3_02/
groundtruth: groundtruth/AnimeGANv3_02/gt.jpg
test_script: test_scripts/AnimeGANv3_02/test_script.py
multi_output: false
