taskid: StyleTransfer_02
result: test_results/StyleTransfer_02/results.jsonl
output_dir: output/StyleTransfer_02/
groundtruth: groundtruth/StyleTransfer_02/gt.jpg
test_script: test_scripts/StyleTransfer_02/test_script.py
multi_output: false
