taskid: TransparentBackground_01
result: test_results/TransparentBackground_01/results.jsonl
output_dir: output/TransparentBackground_01/
groundtruth: groundtruth/TransparentBackground_01/gt.jpg
test_script: test_scripts/TransparentBackground_01/test_script.py
multi_output: false
