taskid: PyPDF2_02
result: test_results/PyPDF2_02/results.jsonl
output_dir: output/PyPDF2_02/
groundtruth: groundtruth/PyPDF2_02/gt/
test_script: test_scripts/PyPDF2_02/test_script.py
multi_output: true
