taskid: AnimeGANv3_03
result: test_results/AnimeGANv3_03/results.jsonl
output_dir: output/AnimeGANv3_03/
groundtruth: groundtruth/AnimeGANv3_03/gt.mp4
test_script: test_scripts/AnimeGANv3_03/test_script.py
multi_output: false
