taskid: PDFPlumber_02
result: test_results/PDFPlumber_02/results.jsonl
output_dir: output/PDFPlumber_02/
groundtruth: groundtruth/PDFPlumber_02/gt.csv
test_script: test_scripts/PDFPlumber_02/test_script.py
multi_output: false
