taskid: Faker_03
result: test_results/Faker_03/results.jsonl
output_dir: output/Faker_03/
groundtruth: groundtruth/Faker_03/gt.txt
test_script: test_scripts/Faker_03/test_script.py
multi_output: false
