taskid: TransparentBackground_03
result: test_results/TransparentBackground_03/results.jsonl
output_dir: output/TransparentBackground_03/
groundtruth: groundtruth/TransparentBackground_03/gt.jpg
test_script: test_scripts/TransparentBackground_03/test_script.py
multi_output: false
