taskid: AnimeGANv3_01
result: test_results/AnimeGANv3_01/results.jsonl
output_dir: output/AnimeGANv3_01/
groundtruth: groundtruth/AnimeGANv3_01/gt.png
test_script: test_scripts/AnimeGANv3_01/test_script.py
multi_output: false
