taskid: Stegano_01
result: test_results/Stegano_01/results.jsonl
output_dir: output/Stegano_01/
groundtruth: groundtruth/Stegano_01/gt.png
test_script: test_scripts/Stegano_01/test_script.py
multi_output: false
parameters:
 watermark: 'stegano'