taskid: Stegano_03
result: test_results/Stegano_03/results.jsonl
output_dir: output/Stegano_03/
groundtruth: groundtruth/Stegano_03/gt.png
test_script: test_scripts/Stegano_03/test_script.py
multi_output: false
parameters:
 watermark: 'hidden_text'